language: haskell
cabal: "3.0"
ghc:
  - "8.4.4"
  - "8.6.5"

install:
  - |
    ghc --version
    cabal --version
    cabal update
    cabal build --enable-tests --enable-benchmarks

script:
  - |
    cabal test --enable-tests
